// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramBot.Web.Infrastructure.Persistences;

#nullable disable

namespace TelegramBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609132908_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramBot.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-11d3-9a0c-0305e82c3301"),
                            Author = "Джордж Оруэлл",
                            Description = "Классический роман о тоталитарном обществе будущего.",
                            Genre = "Антиутопия",
                            Price = 319m,
                            Slug = "1984-novyy-perevod-2918634",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            Author = "Федор Достоевский",
                            Description = "История о нравственном выборе и искуплении.",
                            Genre = "Роман",
                            Price = 309m,
                            Slug = "prestuplenie-i-nakazanie-2465295",
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = new Guid("21ec2020-3aea-4069-a2dd-08002b30309d"),
                            Author = "Джейн Остин",
                            Description = "Романтическая история в английском обществе XIX века.",
                            Genre = "Роман",
                            Price = 290m,
                            Slug = "gordost-i-predubezhdenie-3072633",
                            Title = "Гордость и предубеждение"
                        },
                        new
                        {
                            Id = new Guid("6f9619ff-8b86-d011-b42d-00cf4fc964ff"),
                            Author = "Артур Конан Дойл",
                            Description = "Сборник историй о знаменитом детективе.",
                            Genre = "Детектив",
                            Price = 337m,
                            Slug = "priklyucheniya-sherloka-holmsa-2925677",
                            Title = "Приключения Шерлока Холмса"
                        },
                        new
                        {
                            Id = new Guid("16fd2706-8baf-433b-82eb-8c7fada847da"),
                            Author = "Марк Твен",
                            Description = "История приключений мальчика в США XIX века.",
                            Genre = "Повесть",
                            Price = 319m,
                            Slug = "priklyucheniya-toma-soyera-il-v-galdyaeva-2952874",
                            Title = "Приключения Тома Сойера"
                        },
                        new
                        {
                            Id = new Guid("9a9b8c6e-5f60-4aeb-9445-ffad474fb3f2"),
                            Author = "Лев Толстой",
                            Description = "Масштабный роман о судьбах людей на фоне войны.",
                            Genre = "Эпопея",
                            Price = 347m,
                            Slug = "voyna-i-mir-kniga-1-tt-1-2-roman-2471823",
                            Title = "Война и мир"
                        });
                });

            modelBuilder.Entity("TelegramBot.Domain.Entities.Dialogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dialogues");
                });
#pragma warning restore 612, 618
        }
    }
}
